 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdbool.h>
#include "gpio.h"
#include "utility.h"
#include "armcortexm4.h"
#include "timer.h"
void TIM3_IRQHandler(void)
{
	static uint16_t counter = 0;
	static uint8_t dutyCycle = 10;
	if(TIMER3->TIMx_SR & (1u << 0))
	  {
		  counter++;
		  TIMER3->TIMx_SR &= ~(1u << 0);
		  if(counter >= 1000)
		  {
			  counter = 0;
			  TIMER3->TIMx_CCR1 = dutyCycle;
			  dutyCycle += 10;
		  }
		  if(dutyCycle == 110)
			  	 dutyCycle = 0;
	  }
}
int main(void)
{
			   GPIO_Handle_t PWM_TIMER3_CH1_PB4 = {  .PORTNAME = GPIOB,
								.PINCONF.PIN = GPIO_PIN_4,
								.PINCONF.MODE = GPIO_MODE_ALTARNATE,
								.PINCONF.OTYPE = GPIO_OTYPE_PP,
								.PINCONF.OSPEED = GPIO_OSPEED_HIGH,
								.PINCONF.PUPD = GPIO_PUPD_PU,
								.PINCONF.AF = AF2
								  };
				gpioInit(&PWM_TIMER3_CH1_PB4);
				 
				timerxConfig(TIMER3, 160, 100);   	// (100kHz) 10us counting, 1ms PWM period	1kHz PWM freq
				timer3InterruptEnable();
				timerxPeripheralEnable(TIMER3);
				timer3PwmEnable(DUTY_CYCLE_0);
				 
				while (1)
				{
				}
}
